"""
Multi-channel notification delivery — dashboard push, email digest, and logging.
Relocated to backend/core/alerts/notification_channels.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional

from alerts.alert_models import Alert
from config.settings import SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, ALERT_EMAIL_RECIPIENTS


class DashboardNotifier:
    """Push notifications to the web dashboard."""
    def __init__(self):
        self.pending_notifications = []

    def push(self, alert: Alert) -> bool:
        self.pending_notifications.append({
            "id": alert.alert_id, "type": alert.alert_type, "message": alert.message,
            "severity": alert.severity, "store_id": alert.store_id,
            "timestamp": alert.created_at or datetime.now().isoformat(),
            "action": alert.suggested_action, "corrective_action": alert.corrective_action,
        })
        return True

    def get_pending(self, clear: bool = True) -> list:
        notifications = list(self.pending_notifications)
        if clear:
            self.pending_notifications.clear()
        return notifications

    @property
    def count(self) -> int:
        return len(self.pending_notifications)


class EmailNotifier:
    """Email digest notifications via SMTP."""
    def __init__(self):
        self.enabled = bool(SMTP_USER and SMTP_PASSWORD)

    def send_digest(self, alerts: list, subject: str = "ShelfIQ Alert Digest") -> bool:
        if not self.enabled:
            self._log_email(alerts, subject)
            return False
        try:
            html = self._build_html(alerts)
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = SMTP_USER
            msg["To"] = ", ".join(ALERT_EMAIL_RECIPIENTS)
            msg.attach(MIMEText(html, "html"))
            with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
                server.starttls()
                server.login(SMTP_USER, SMTP_PASSWORD)
                server.send_message(msg)
            return True
        except Exception as e:
            print(f"  Email send failed: {e}")
            self._log_email(alerts, subject)
            return False

    def _build_html(self, alerts: list) -> str:
        severity_colors = {5: "#dc3545", 4: "#e83e8c", 3: "#fd7e14", 2: "#ffc107", 1: "#17a2b8"}
        rows = ""
        for a in alerts:
            sev = a.severity if isinstance(a, Alert) else a.get("severity", 1)
            color = severity_colors.get(sev, "#6c757d")
            msg = a.message if isinstance(a, Alert) else a.get("message", "")
            atype = a.alert_type if isinstance(a, Alert) else a.get("alert_type", "")
            store = a.store_id if isinstance(a, Alert) else a.get("store_id", "")
            rows += f'<tr><td style="border-left:4px solid {color};padding:8px">{atype}</td><td style="padding:8px">{store}</td><td style="padding:8px">{msg}</td></tr>'
        return f'<html><body style="font-family:Arial,sans-serif;background:#f8f9fa;padding:20px"><div style="max-width:600px;margin:auto;background:white;border-radius:8px;padding:20px"><h2>ShelfIQ Alert Digest</h2><p>{len(alerts)} alert(s) require attention:</p><table style="width:100%;border-collapse:collapse"><tr style="background:#f1f1f1"><th style="padding:8px;text-align:left">Type</th><th style="padding:8px;text-align:left">Store</th><th style="padding:8px;text-align:left">Message</th></tr>{rows}</table><p style="margin-top:20px;font-size:12px;color:#888">Generated by ShelfIQ at {datetime.now().strftime("%Y-%m-%d %H:%M")}</p></div></body></html>'

    def _log_email(self, alerts: list, subject: str):
        print(f"  [EMAIL LOG] {subject} - {len(alerts)} alerts")
        for a in alerts[:3]:
            msg = a.message if isinstance(a, Alert) else a.get("message", "")
            print(f"     -> {msg}")


class NotificationRouter:
    """Routes alerts to appropriate notification channels."""
    def __init__(self):
        self.dashboard = DashboardNotifier()
        self.email = EmailNotifier()

    def notify(self, alert: Alert, channels: list = None):
        channels = channels or ["dashboard"]
        for ch in channels:
            if ch == "dashboard": self.dashboard.push(alert)
            elif ch == "email":   self.email.send_digest([alert])

    def notify_batch(self, alerts: list, channels: list = None):
        channels = channels or ["dashboard"]
        for alert in alerts:
            self.notify(alert, channels)
        if "email" in (channels or []):
            self.email.send_digest(alerts)

    def get_dashboard_notifications(self) -> list:
        return self.dashboard.get_pending()


notifier = NotificationRouter()
